# Welcome to Jekyll!
#

# Site settings
title: Montreal Blog
description: |
  A blog by two kiwis living in Montreal.
owner: Holly # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: none@none.none
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://montreal-blog.henryjenkins.name" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/Geeze-Louise
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
exclude: [CNAME, README.md, Gemfile, Gemfile.lock]
